defaults:  
  - _self_

# ## whether test a single file or a directory
# inFile: akira.json
# CTI_Source: AVERTIUM

## compare inSet with ground_truth_set
inSet: /home/yutong/CTINexus/dataset/Merger-output-large-GT

## output evaluation results into the outSet
outSet: /home/yutong/CTINexus/dataset/Merger-output-large-GT-proc