defaults:  
  - _self_

# ## whether test a single file or a directory
# inFile: akira.json
# CTI_Source: AVERTIUM

## compare inSet with ground_truth_set
ground_truth_set: /home/yutong/CTINexus/dataset/Tagger-output-gpt4-8-v2
inSet: /home/yutong/CTINexus/Eval/RQ3/Tagger/GPT4-8shot

## output evaluation results into the outSet
outSet: /home/yutong/CTINexus/Eval/RQ3/Tagger/GPT4-8shot
outMetricSet: /home/yutong/CTINexus/Eval/RQ3/Tagger/GPT4-8shot/prompt_store/metrics

shot: 8
base_model: gpt-4-0125-preview