name: grace_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip=21.2.4
  - python=3.9.7
  - pip:
    - hydra-core==1.2.0
    - openai==0.28
    - jinja==3.1.3
    - MarkupSafe==2.1.5
    - numpy==1.26.4 
    - scipy==1.13.0
