defaults:  
  - _self_

# ## whether test a single file or a directory
# inFile: akira.json
# CTI_Source: securityweek #report error while running

## compare inSet with ground_truth_set
ground_truth_set: /home/yutong/CTINexus/dataset/RE-IE-outputs-3-asc
inSet: /home/yutong/CTINexus/Eval/RQ2/DemoNum/4

## output evaluation results into the outSet
outSet: /home/yutong/CTINexus/Eval/RQ2/DemoNum/4-eval-v1
outMetricSet: /home/yutong/CTINexus/Eval/RQ2/DemoNum/4-eval-v1/prompt_store/metrics

## openAI setting
openai_key: <YOUR_OPENAI_KEY>
embedding_model: text-embedding-3-large
thresh: 0.7