defaults:  
  - _self_

# ## whether test a single file or a directory
# inFile: akira.json
# CTI_Source: AVERTIUM

## compare inSet with ground_truth_set
ground_truth_set: /home/yutong/CTINexus/dataset/RE-IE-outputs-3-asc
inSet: /home/yutong/CTINexus/Eval/RQ2/DemoNum/3

## output evaluation results into the outSet
outSet: /home/yutong/CTINexus/Eval/RQ2/DemoNum/3-eval-RE-v3
outMetricSet: /home/yutong/CTINexus/Eval/RQ2/DemoNum/3-eval-RE-v3/prompt_store/metrics

## openAI setting
openai_key: <YOUR_OPENAI_KEY>
embedding_model: text-embedding-3-large
thresh: 0.8
