defaults:  
  - _self_

CTI_Source: AVERTIUM
temp: Q3.jinja
sysMsg: "3"
model: gpt-4-0125-preview
IFjson: 1
inFile: null
inFolder: 1
IFGT: 1
IFsys: 0
Tagged_set: dataset/Tagger-outputs


# CTI_Source=Google_TAG 