defaults:  
  - _self_

# inFile: 
# CTI_source: 
inSet: /home/yutong/CTINexus/dataset/RE-IE-outputs-3-asc
outSet: /home/yutong/CTINexus/Eval/RQ3/Tagger/GPT3.5-1shot

# OpenAI setting
model: gpt-3.5-turbo-0125
api_key: <YOUR_OPENAI_KEY>

# Prompt setting
tag_prompt_folder: Toolbox/TagPrompt
tag_prompt_file: 1shot.jinja
tag_prompt_store: /home/yutong/CTINexus/Eval/RQ3/Tagger/GPT3.5-1shot/prompt_store
shot: 1