defaults:  
  - _self_

# inFile: 
# CTI_source: 
inSet: /home/yutong/CTINexus/dataset/RE-IE-outputs-3-asc
outSet: /home/yutong/CTINexus/Eval/RQ3/Tagger/GPT4-12shot

# OpenAI setting
model: gpt-4-0125-preview
api_key: <YOUR_OPENAI_KEY>

# Prompt setting
tag_prompt_folder: Toolbox/TagPrompt
tag_prompt_file: 12shot.jinja
tag_prompt_store: /home/yutong/CTINexus/Eval/RQ3/Tagger/GPT4-12shot/prompt_store
shot: 12
