defaults:  
  - _self_

# inFile: 
# CTI_source: 
inSet: /home/yutong/CTINexus/dataset/RE-IE-outputs-3-asc  ##ground truth of triplet extraction
outSet: /home/yutong/CTINexus/dataset/Tagger-output-gpt4-8-v2 ##tagger ground truth

# OpenAI setting
model: gpt-4-0125-preview
api_key: <YOUR_OPENAI_KEY>

# Prompt setting
tag_prompt_folder: Toolbox/TagPrompt
tag_prompt_file: 8shot-v2.jinja
tag_prompt_store: /home/yutong/CTINexus/dataset/Tagger-output-gpt4-8-v2/prompt_store
shot: 8