defaults:  
  - _self_

# CTI_Source: AVERTIUM
# inFile: akira-S18-NL2.json
inSet: /home/yutong/CTINexus/dataset/Tagger-output-gpt4-8-v2-processed
outSet: /home/yutong/CTINexus/Eval/RQ3/Merger/Embedding/Merger-output-0.6-small
api_key: <YOUR_OPENAI_KEY>
embedding_model: text-embedding-3-small
similarity_threshold: 0.6