defaults:  
  - _self_

# CTI_Source: AVERTIUM
# inFile: akira-S18-NL2.json
inSet: /home/yutong/CTINexus/dataset/Tagger-output-gpt4-8-v2-processed
outSet: /home/yutong/CTINexus/dataset/Merger-output-large-0.6
api_key: <YOUR_OPENAI_KEY>
embedding_model: text-embedding-3-large
similarity_threshold: 0.6