defaults:  
  - _self_

CTI_Source: threatPost
# inFile: akira-S18-NL2.json
inSet: /home/yutong/CTINexus/dataset/Tagger-output-gpt4-8-v2-processed
outSet: /home/yutong/CTINexus/Eval/RQ3/Merger/Threshold/Merger-output-large-0.4
api_key: <YOUR_OPENAI_KEY>
embedding_model: text-embedding-3-large
similarity_threshold: 0.4