defaults:  
  - _self_

# CTI_Source: AVERTIUM
# inFile: akira.json
inSet: /home/yutong/CTINexus/dataset/Merger-output-large-GT
outSet: /home/yutong/CTINexus/Eval/RQ3/Linker/0-shot-gpt-3.5

## oepnai config
model: gpt-3.5-turbo-0125
api_key: <YOUR_OPENAI_KEY>


## prompt constructor
link_prompt_folder: Toolbox/LinkerPrompt
link_prompt_file: 0-shot.jinja
shot: 0

## prompt store
link_prompt_set: /home/yutong/CTINexus/Eval/RQ3/Linker/0-shot-gpt-3.5/prompt_store/metrics