defaults:  
  - _self_

addition: 
  BleepingComputer:
    - androxgh0st.json
  Microsoft:
    - diamond-sleet.json
    - north-korean.json
    - teamcity-cve.json
  securityweek:
    - wallescape.json
  symantec:
    - Follina.json
  thehackernews:
    - ESG.json
    - OfBiz.json
  threatPost:
    - H0lyGh0st.json
    - Hikvision.json
# CTI_Source: AVERTIUM
# inFile: akira.json
inSet: /home/yutong/CTINexus/dataset/Merger-output-large-GT
outSet: /home/yutong/CTINexus/Eval/RQ3/Linker/1-shot-gpt-4

## oepnai config
model: gpt-4-0125-preview
api_key: <YOUR_OPENAI_KEY>


## prompt constructor
link_prompt_folder: Toolbox/LinkerPrompt
link_prompt_file: 1-shot.jinja
shot: 1

## prompt store
link_prompt_set: /home/yutong/CTINexus/Eval/RQ3/Linker/1-shot-gpt-4/prompt_store/metrics