defaults:  
  - _self_

# CTI_Source: AVERTIUM
# inFile: akira.json
addition: 
  darkreading:
    - apache-activemq.json
    - Microsoft-Outlook.json
    - SolarWinds-Style.json
  thehackernews:
    - OfBiz.json
  trendmicro:
    - Akira.json

inSet: /home/yutong/CTINexus/dataset/Merger-output-large-GT
outSet: /home/yutong/CTINexus/Eval/RQ3/Linker/2-shot-gpt-3.5-RE

## oepnai config
model: gpt-3.5-turbo-0125
api_key: <YOUR_OPENAI_KEY>


## prompt constructor
link_prompt_folder: Toolbox/LinkerPrompt
link_prompt_file: 2-shot.jinja
shot: 2

## prompt store
link_prompt_set: /home/yutong/CTINexus/Eval/RQ3/Linker/2-shot-gpt-3.5-RE/prompt_store/metrics