defaults:  
  - _self_

# CTI_Source: AVERTIUM
# inFile: akira-S18-NL2.json
evalSet: /home/yutong/CTINexus/Eval/RQ3/Merger/Threshold/Merger-output-large-0.4
GTSet: /home/yutong/CTINexus/dataset/Merger-output-large-GT
similarity_threshold: 0.4