defaults:  
  - _self_

# CTI_Source: AVERTIUM

inSet: /home/yutong/CTINexus/Eval/RQ3/Linker/0-shot-gpt-4
outSet: /home/yutong/CTINexus/Eval/RQ3/Linker/0-shot-gpt-4
GTSet: /home/yutong/CTINexus/dataset/Linker-outputs-GT

embedding_model: text-embedding-3-large
api_key: <YOUR_OPENAI_KEY>
thresh: 0.45