defaults:  
  - _self_

# CTI_Source: AVERTIUM
inSet: /home/yutong/CTINexus/Eval/RQ3/Linker/1-shot-gpt-3.5-RE
outSet: /home/yutong/CTINexus/Eval/RQ3/Linker/1-shot-gpt-3.5-RE
GTSet: /home/yutong/CTINexus/dataset/Linker-outputs-GT

embedding_model: text-embedding-3-large
api_key: <YOUR_OPENAI_KEY>
thresh: 0.45