defaults:  
  - _self_

### basic setting
# inFile: VenomRAT.json
# CTI_Source: Unit42
inSet: dataset/IE-inputs
outSet: /home/yutong/CTINexus/Eval/RQ2/Backbone/GPT-3.5

### openAI setting
model: gpt-3.5-turbo-0125
api_key: <YOUR_OPENAI_KEY>

### demonstration setting
retriever:
  type: "kNN" #retriever type
  permutation: asc #the permutation of the kNN
shot: 2 #k of the kNN
demo_set: /home/yutong/CTINexus/dataset/RE-IE-outputs-3-asc #store the demos(also the current ground truth)

### prompt setting
ie_prompt_set: Toolbox/IE_Prompts #the folder stored the prompt templates 
templ: QD1.jinja #used promt template
ie_prompt_store: /home/yutong/CTINexus/Eval/RQ2/Backbone/GPT-3.5/prompt_store #store the prompt used for each CTI report